### ISSUE TITLE
test case needed

### ISSUE THREAD

**Issue by ktarbet** [gunnarleffler/hydroJSON#2]
https://github.com/18F/api-standards mentions: 
### Using one's own API

The #1 best way to understand and address the weaknesses in an API's design and implementation is to use it in a production system.

Whenever feasible, design an API in parallel with an accompanying integration of that API.

**Comment by gunnarleffler** [comment]
Karl,

I updated the reference implementation to accommodate the Pisces schema issues we discussed a few weeks ago. let me know if this works for you.
